server:
  port: 5000

#spring:
#  profiles:
#    active: demo
app:
  datasource:
    jdbc-url: jdbc:postgresql://claims.c5y4t1dqrn9g.eu-west-1.rds.amazonaws.com:5432/claims
    username: postgres
    password: farooq135
    pool-size: 30


